dental-backend:
    resource: "@DentalBundle/Resources/config/routing.yml"
    prefix:   /backend


NelmioApiDocBundle:
    resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
    prefix:   /doc
