<?php

namespace DentalBundle\Repository;

/**
 * usuariosRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class usuariosRepository extends \Doctrine\ORM\EntityRepository
{
    
}
